-- Roam: apply all migrations to an EMPTY Supabase database.-- Dashboard -> SQL Editor -> New query -> paste entire file -> Run-- Regenerated by: pnpm supabase:bundle (45 files)

-- ========== 20240001000000_create_tables.sql ==========
-- Migration 001: Create all tables (Roam Choreography V1)
-- Tables created in dependency order.

-- 1. users — links to Supabase Auth
CREATE TABLE users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'creator', 'pro', 'studio')),
  created_at timestamptz DEFAULT now()
);

-- 2. sessions — FK to users
CREATE TABLE sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 3. music_tracks — FK to sessions
CREATE TABLE music_tracks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  source_type text NOT NULL CHECK (source_type IN ('upload', 'youtube')),
  source_url text,
  storage_path text,
  bpm float,
  beat_grid jsonb,
  sections jsonb DEFAULT '[]',
  analysis_status text DEFAULT 'pending' CHECK (analysis_status IN ('pending', 'processing', 'complete', 'failed')),
  created_at timestamptz DEFAULT now()
);

-- 4. clips — FK to sessions
CREATE TABLE clips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  local_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'Clip',
  mux_upload_id text,
  mux_asset_id text UNIQUE,
  mux_playback_id text,
  mux_passthrough jsonb,
  upload_status text NOT NULL DEFAULT 'local' CHECK (upload_status IN ('local', 'queued', 'uploading', 'processing', 'ready', 'failed')),
  move_name text,
  style text,
  energy text,
  difficulty text,
  bpm integer,
  notes text,
  recorded_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE (session_id, local_id)
);

-- 5. analysis_jobs — FKs to sessions and music_tracks
CREATE TABLE analysis_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  music_track_id uuid NOT NULL REFERENCES music_tracks(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'complete', 'failed')),
  attempt_count integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  claimed_at timestamptz,
  lease_expires_at timestamptz,
  completed_at timestamptz,
  timeout_at timestamptz,
  error text
);

-- 7. claim_analysis_job RPC: atomically claim a single pending job
create or replace function claim_analysis_job()
returns setof analysis_jobs
language sql
as $$
  update analysis_jobs
  set
    status = 'processing',
    claimed_at = now(),
    lease_expires_at = now() + interval '60 seconds'
  where id = (
    select id
    from analysis_jobs
    where status = 'pending'
    and (timeout_at is null or timeout_at > now())
    order by created_at
    for update skip locked
    limit 1
  )
  returning *;
$$;

-- 6. share_tokens — FK to sessions
CREATE TABLE share_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  token uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  revoked_at timestamptz
);

-- ========== 20240002000000_create_indexes.sql ==========
-- Migration 002: Create indexes (Roam Choreography V1)

CREATE INDEX ON share_tokens(token);

CREATE INDEX ON clips(session_id, upload_status);

CREATE INDEX ON clips(session_id, recorded_at DESC);

CREATE INDEX ON analysis_jobs(status, timeout_at);

-- ========== 20240003000000_rls_policies.sql ==========
-- Migration 003: Enable RLS and create policies (Roam Choreography V1)

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE music_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE share_tokens ENABLE ROW LEVEL SECURITY;

-- users: own row only
CREATE POLICY users_select_own ON users FOR SELECT USING (id = auth.uid());
CREATE POLICY users_update_own ON users FOR UPDATE USING (id = auth.uid());

-- sessions: all operations for own sessions
CREATE POLICY sessions_all_own ON sessions FOR ALL USING (user_id = auth.uid());

-- music_tracks: all operations where session belongs to user
CREATE POLICY music_tracks_all_own_session ON music_tracks FOR ALL
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

-- clips: all operations where session belongs to user
CREATE POLICY clips_all_own_session ON clips FOR ALL
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

-- analysis_jobs: API (authenticated) can INSERT jobs for own sessions; service_role has explicit full access
CREATE POLICY analysis_jobs_insert_own_session ON analysis_jobs FOR INSERT
  TO authenticated
  WITH CHECK (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY analysis_jobs_service_role_all ON analysis_jobs FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- share_tokens: owner can SELECT/INSERT/UPDATE/DELETE; anon SELECT for token-scoped non-revoked access
CREATE POLICY share_tokens_select_anon ON share_tokens FOR SELECT
  TO anon
  USING (
    revoked_at IS NULL
    AND token = NULLIF(trim(current_setting('app.requested_share_token', true)), '')::uuid
  );
CREATE POLICY share_tokens_select_own_session ON share_tokens FOR SELECT
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY share_tokens_insert_own_session ON share_tokens FOR INSERT
  WITH CHECK (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY share_tokens_update_own_session ON share_tokens FOR UPDATE
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY share_tokens_delete_own_session ON share_tokens FOR DELETE
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

-- ========== 20240004000000_get_shared_session_rpc.sql ==========
-- Migration 004: get_shared_session RPC (anon-accessible share page)

CREATE OR REPLACE FUNCTION get_shared_session(p_token uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
  v_session sessions%ROWTYPE;
  v_music_track music_tracks%ROWTYPE;
  v_clips jsonb;
BEGIN
  -- Look up valid share token
  SELECT st.session_id INTO v_session_id
  FROM share_tokens st
  WHERE st.token = p_token AND st.revoked_at IS NULL AND st.clip_id IS NULL;

  IF v_session_id IS NULL THEN
    RETURN NULL;
  END IF;

  -- Fetch session
  SELECT * INTO v_session FROM sessions WHERE id = v_session_id;

  -- Fetch single music_track (V1: one track per session)
  SELECT * INTO v_music_track
  FROM music_tracks
  WHERE session_id = v_session_id
  LIMIT 1;

  -- Fetch clips with upload_status IN ('ready', 'processing'), ordered by recorded_at ASC
  SELECT COALESCE(
    (SELECT jsonb_agg(to_jsonb(cl) ORDER BY cl.recorded_at ASC)
     FROM clips cl
     WHERE cl.session_id = v_session_id AND cl.upload_status IN ('ready', 'processing')),
    '[]'::jsonb
  ) INTO v_clips;

  RETURN json_build_object(
    'session', to_jsonb(v_session),
    'music_track', CASE WHEN v_music_track.id IS NULL THEN NULL ELSE to_jsonb(v_music_track) END,
    'clips', COALESCE(v_clips, '[]'::jsonb)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION get_shared_session(uuid) TO anon;

-- ========== 20240005000000_music_track_offset.sql ==========
ALTER TABLE music_tracks ADD COLUMN IF NOT EXISTS downbeat_offset_ms float DEFAULT 0;

-- ========== 20240006000000_users_plan.sql ==========
-- Migration 006: Extend users table with Stripe columns and auto-insert trigger

ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, plan)
  VALUES (NEW.id, NEW.email, 'free')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE handle_new_user();

-- Service role needs full access to users (for API webhooks and billing)
CREATE POLICY users_service_role_all ON users
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- ========== 20240007000000_fix_claim_analysis_job.sql ==========
-- Migration 007: Fix claim_analysis_job for already-migrated environments
-- Ensures no claim-time attempt_count increment and timeout_at validity guard.
-- Historical migration 001 is unchanged; this migration rolls out the fix.

create or replace function claim_analysis_job()
returns setof analysis_jobs
language sql
as $$
  update analysis_jobs
  set
    status = 'processing',
    claimed_at = now(),
    lease_expires_at = now() + interval '60 seconds'
  where id = (
    select id
    from analysis_jobs
    where status = 'pending'
    and (timeout_at is null or timeout_at > now())
    order by created_at
    for update skip locked
    limit 1
  )
  returning *;
$$;

-- ========== 20240008000000_claim_sets_timeout_at.sql ==========
-- Migration 008: Extend claim_analysis_job to set timeout_at at claim time
-- Ensures every claimed job has a valid, non-NULL timeout_at for the analyzer
-- and eliminates KeyError on job["timeout_at"] in main.py.

create or replace function claim_analysis_job()
returns setof analysis_jobs
language sql
as $$
  update analysis_jobs
  set
    status = 'processing',
    claimed_at = now(),
    lease_expires_at = now() + interval '60 seconds',
    timeout_at = now() + interval '5 minutes'
  where id = (
    select id
    from analysis_jobs
    where status = 'pending'
    and (timeout_at is null or timeout_at > now())
    order by created_at
    for update skip locked
    limit 1
  )
  returning *;
$$;

-- ========== 20240009000000_claim_sets_timeout_at_when_null.sql ==========
-- Migration 009: Fix claim_analysis_job for already-migrated databases
-- Sets timeout_at only when null (no overwrite). Keeps same atomic claim and
-- timeout guard behavior. Historical 008 unchanged; this migration ensures
-- production and other upgraded databases receive the runtime fix.

create or replace function claim_analysis_job()
returns setof analysis_jobs
language sql
as $$
  update analysis_jobs
  set
    status = 'processing',
    claimed_at = now(),
    lease_expires_at = now() + interval '60 seconds',
    timeout_at = coalesce(timeout_at, now() + interval '5 minutes')
  where id = (
    select id
    from analysis_jobs
    where status = 'pending'
    and (timeout_at is null or timeout_at > now())
    order by created_at
    for update skip locked
    limit 1
  )
  returning *;
$$;

-- ========== 20240010000000_v1_feedback.sql ==========
-- Migration 010: V1 feedback tables (feedback_requests, clip_comments)
-- Idempotent: IF NOT EXISTS for tables; DROP IF EXISTS for policies before CREATE.

CREATE TABLE IF NOT EXISTS feedback_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  created_at timestamptz DEFAULT now(),
  UNIQUE(clip_id)
);

CREATE TABLE IF NOT EXISTS clip_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  timecode_ms integer NOT NULL,
  text text NOT NULL,
  commenter_name text,
  created_at timestamptz DEFAULT now()
);

-- Add uniqueness if table already existed from combined migration
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'feedback_requests_clip_id_key'
  ) AND EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'feedback_requests') THEN
    ALTER TABLE feedback_requests ADD CONSTRAINT feedback_requests_clip_id_key UNIQUE (clip_id);
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE feedback_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE clip_comments ENABLE ROW LEVEL SECURITY;

-- feedback_requests: owner SELECT/INSERT/UPDATE via session → user; NO anon SELECT
DROP POLICY IF EXISTS feedback_requests_select_anon_open ON feedback_requests;
DROP POLICY IF EXISTS feedback_requests_select_own ON feedback_requests;
DROP POLICY IF EXISTS feedback_requests_insert_own ON feedback_requests;
DROP POLICY IF EXISTS feedback_requests_update_own ON feedback_requests;
CREATE POLICY feedback_requests_select_own ON feedback_requests FOR SELECT
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY feedback_requests_insert_own ON feedback_requests FOR INSERT
  WITH CHECK (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY feedback_requests_update_own ON feedback_requests FOR UPDATE
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

-- clip_comments: owner SELECT via session → user; anon INSERT only; NO anon SELECT
DROP POLICY IF EXISTS clip_comments_select_anon ON clip_comments;
DROP POLICY IF EXISTS clip_comments_select_own ON clip_comments;
DROP POLICY IF EXISTS clip_comments_insert_anon ON clip_comments;
CREATE POLICY clip_comments_select_own ON clip_comments FOR SELECT
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));
CREATE POLICY clip_comments_insert_anon ON clip_comments FOR INSERT
  TO anon
  WITH CHECK (true);

-- ========== 20240011000000_v1_annotations.sql ==========
-- Migration 011: V1 clip_annotations table
-- Idempotent: IF NOT EXISTS for table; DROP IF EXISTS for policies before CREATE.

CREATE TABLE IF NOT EXISTS clip_annotations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  timecode_ms integer NOT NULL,
  type text NOT NULL CHECK (type IN ('text', 'arrow', 'circle')),
  payload jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE clip_annotations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clip_annotations_all_own ON clip_annotations;
CREATE POLICY clip_annotations_all_own ON clip_annotations FOR ALL
  USING (clip_id IN (
    SELECT c.id FROM clips c
    INNER JOIN sessions s ON c.session_id = s.id
    WHERE s.user_id = auth.uid()
  ));

-- ========== 20240012000000_v1_tag_history.sql ==========
-- Migration 012: V1 clip_tag_history table
-- Idempotent: IF NOT EXISTS for table; DROP IF EXISTS for policies before CREATE.

CREATE TABLE IF NOT EXISTS clip_tag_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  snapshot jsonb NOT NULL,
  saved_at timestamptz DEFAULT now(),
  saved_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE clip_tag_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clip_tag_history_all_own ON clip_tag_history;
CREATE POLICY clip_tag_history_all_own ON clip_tag_history FOR ALL
  USING (clip_id IN (
    SELECT c.id FROM clips c
    INNER JOIN sessions s ON c.session_id = s.id
    WHERE s.user_id = auth.uid()
  ));

-- ========== 20240015000000_v1_assembly.sql ==========
-- Migration 013: V1 section_clips table and constraint/index
-- Idempotent: IF NOT EXISTS for table and constraint; DROP IF EXISTS for policies before CREATE.

CREATE TABLE IF NOT EXISTS section_clips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  section_label text NOT NULL,
  section_start_ms integer NOT NULL,
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  position integer NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Add UNIQUE(session_id, clip_id) DEFERRABLE if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'section_clips_session_clip_unique'
  ) AND EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'section_clips') THEN
    ALTER TABLE section_clips ADD CONSTRAINT section_clips_session_clip_unique
      UNIQUE (session_id, clip_id) DEFERRABLE INITIALLY DEFERRED;
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Composite index for ordered assembly fetch (GET /sessions/:id/assembly)
CREATE INDEX IF NOT EXISTS idx_section_clips_order ON section_clips (session_id, section_start_ms, position);

ALTER TABLE section_clips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS section_clips_all_own ON section_clips;
CREATE POLICY section_clips_all_own ON section_clips FOR ALL
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

-- ========== 20240016000000_update_clip_tags_with_history_rpc.sql ==========
-- RPC for atomic tag update: snapshot history + update clips in one transaction.
-- Ensures version-history row is created before applying tag updates.

CREATE OR REPLACE FUNCTION update_clip_tags_with_history(
  p_clip_id uuid,
  p_user_id uuid,
  p_snapshot jsonb,
  p_updates jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_clip_ok boolean;
  v_updated jsonb;
BEGIN
  -- 1. Verify clip belongs to user via session
  SELECT EXISTS(
    SELECT 1 FROM clips c
    INNER JOIN sessions s ON c.session_id = s.id
    WHERE c.id = p_clip_id AND s.user_id = p_user_id
  ) INTO v_clip_ok;
  IF NOT v_clip_ok THEN
    RAISE EXCEPTION 'Clip not found or access denied' USING errcode = 'P0001';
  END IF;

  -- 2. Insert history snapshot first (must succeed before any update)
  INSERT INTO clip_tag_history (clip_id, snapshot, saved_by)
  VALUES (p_clip_id, p_snapshot, p_user_id);

  -- 3. Apply updates to clips (only fields present in p_updates)
  UPDATE clips
  SET
    move_name = CASE WHEN p_updates ? 'move_name' THEN (p_updates->>'move_name')::text ELSE move_name END,
    style = CASE WHEN p_updates ? 'style' THEN (p_updates->>'style')::text ELSE style END,
    energy = CASE WHEN p_updates ? 'energy' THEN (p_updates->>'energy')::text ELSE energy END,
    difficulty = CASE WHEN p_updates ? 'difficulty' THEN (p_updates->>'difficulty')::text ELSE difficulty END,
    bpm = CASE WHEN p_updates ? 'bpm' THEN (p_updates->'bpm')::integer ELSE bpm END,
    notes = CASE WHEN p_updates ? 'notes' THEN (p_updates->>'notes')::text ELSE notes END
  WHERE id = p_clip_id;

  -- 4. Return updated clip as jsonb
  SELECT to_jsonb(cl) INTO v_updated
  FROM clips cl
  WHERE cl.id = p_clip_id;

  RETURN v_updated;
END;
$$;

-- ========== 20240017000000_replace_section_clips_rpc.sql ==========
-- RPC for atomic assembly replace: delete + insert in one transaction.
-- Validates session ownership and clip_ids before mutating state.

CREATE OR REPLACE FUNCTION replace_section_clips(
  p_session_id uuid,
  p_user_id uuid,
  p_assignments jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_ok boolean;
  v_clip_ids uuid[];
  v_clip_count int;
  v_valid_count int;
  v_a jsonb;
  v_result jsonb;
BEGIN
  -- 1. Verify session belongs to user
  SELECT EXISTS(
    SELECT 1 FROM sessions WHERE id = p_session_id AND user_id = p_user_id
  ) INTO v_session_ok;
  IF NOT v_session_ok THEN
    RAISE EXCEPTION 'Session not found or access denied' USING errcode = 'P0001';
  END IF;

  -- 2. Validate payload: must be array of objects with section_label, section_start_ms, clip_id, position
  IF jsonb_typeof(p_assignments) != 'array' THEN
    RAISE EXCEPTION 'assignments must be an array' USING errcode = 'P0002';
  END IF;

  -- 3. Extract and validate clip_ids exist and belong to session
  FOR v_a IN SELECT * FROM jsonb_array_elements(p_assignments)
  LOOP
    IF v_a->>'clip_id' IS NULL OR v_a->>'section_label' IS NULL
       OR (v_a->'section_start_ms') IS NULL OR (v_a->'position') IS NULL THEN
      RAISE EXCEPTION 'Each assignment must have section_label, section_start_ms, clip_id, position'
        USING errcode = 'P0002';
    END IF;
  END LOOP;

  SELECT COALESCE(array_agg((elem->>'clip_id')::uuid), ARRAY[]::uuid[])
  INTO v_clip_ids
  FROM jsonb_array_elements(p_assignments) AS elem
  WHERE elem->>'clip_id' IS NOT NULL AND elem->>'clip_id' != '';

  SELECT COUNT(*) INTO v_valid_count
  FROM clips c
  WHERE c.id = ANY(v_clip_ids) AND c.session_id = p_session_id;

  SELECT array_length(v_clip_ids, 1) INTO v_clip_count;
  IF v_clip_count IS NULL THEN
    v_clip_count := 0;
  END IF;
  IF v_valid_count != v_clip_count THEN
    RAISE EXCEPTION 'One or more clip_ids are invalid or do not belong to this session'
      USING errcode = 'P0002';
  END IF;

  -- 4. Delete existing + insert new (atomic in one transaction)
  DELETE FROM section_clips WHERE session_id = p_session_id;

  IF v_clip_count > 0 THEN
    INSERT INTO section_clips (session_id, section_label, section_start_ms, clip_id, position)
    SELECT
      p_session_id,
      elem->>'section_label',
      (elem->'section_start_ms')::int,
      (elem->>'clip_id')::uuid,
      (elem->'position')::int
    FROM jsonb_array_elements(p_assignments) AS elem;
  END IF;

  -- 5. Return inserted rows as jsonb array
  SELECT COALESCE(
    (SELECT jsonb_agg(to_jsonb(sc) ORDER BY sc.section_start_ms, sc.position)
     FROM section_clips sc WHERE sc.session_id = p_session_id),
    '[]'::jsonb
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ========== 20240018000000_rls_feedback_uniqueness.sql ==========
-- RLS: Remove permissive anon policies; add token-scoped RPCs for comments and feedback.
-- Feedback: Deduplicate and enforce UNIQUE(clip_id) on feedback_requests.

-- 1. Drop permissive anon SELECT policies
DROP POLICY IF EXISTS clip_comments_select_anon ON clip_comments;
DROP POLICY IF EXISTS feedback_requests_select_anon_open ON feedback_requests;

-- 2. RPC: Get clip comments for a valid share token (anon-accessible)
CREATE OR REPLACE FUNCTION get_clip_comments_for_share(p_token uuid, p_clip_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
  v_clip_ok boolean;
  v_result jsonb;
BEGIN
  SELECT st.session_id INTO v_session_id
  FROM share_tokens st
  WHERE st.token = p_token AND st.revoked_at IS NULL;

  IF v_session_id IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT EXISTS(
    SELECT 1 FROM clips c
    WHERE c.id = p_clip_id AND c.session_id = v_session_id
  ) INTO v_clip_ok;

  IF NOT v_clip_ok THEN
    RETURN '[]'::jsonb;
  END IF;

  SELECT COALESCE(
    (SELECT jsonb_agg(to_jsonb(cc) ORDER BY cc.timecode_ms)
     FROM clip_comments cc
     WHERE cc.clip_id = p_clip_id AND cc.session_id = v_session_id),
    '[]'::jsonb
  ) INTO v_result;

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION get_clip_comments_for_share(uuid, uuid) TO anon;

-- 3. RPC: Get feedback request status for a valid share token (anon-accessible)
CREATE OR REPLACE FUNCTION get_feedback_request_for_share(p_token uuid, p_clip_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
  v_clip_ok boolean;
  v_result jsonb;
BEGIN
  SELECT st.session_id INTO v_session_id
  FROM share_tokens st
  WHERE st.token = p_token AND st.revoked_at IS NULL;

  IF v_session_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT EXISTS(
    SELECT 1 FROM clips c
    WHERE c.id = p_clip_id AND c.session_id = v_session_id
  ) INTO v_clip_ok;

  IF NOT v_clip_ok THEN
    RETURN NULL;
  END IF;

  SELECT to_jsonb(fr) INTO v_result
  FROM feedback_requests fr
  WHERE fr.clip_id = p_clip_id AND fr.session_id = v_session_id
  LIMIT 1;

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION get_feedback_request_for_share(uuid, uuid) TO anon;

-- 4. Deduplicate feedback_requests: keep one row per clip_id (prefer open, then most recent)
DELETE FROM feedback_requests
WHERE id NOT IN (
  SELECT DISTINCT ON (clip_id) id
  FROM feedback_requests
  ORDER BY clip_id, CASE status WHEN 'open' THEN 0 ELSE 1 END, created_at DESC NULLS LAST
);

-- 5. Add UNIQUE constraint on feedback_requests.clip_id (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    WHERE t.relname = 'feedback_requests' AND c.conname IN ('feedback_requests_clip_id_unique', 'feedback_requests_clip_id_key')
  ) THEN
    ALTER TABLE feedback_requests ADD CONSTRAINT feedback_requests_clip_id_unique UNIQUE (clip_id);
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ========== 20240019000000_rpc_security_hardening.sql ==========
-- RPC Security Hardening: Lock mutating SECURITY DEFINER functions to service_role only
--
-- These are mutating SECURITY DEFINER RPCs that must only be callable via the service-role
-- path (i.e., the apps/api server). Direct RPC calls from anon or authenticated roles
-- are blocked at the permission level.
--
-- The API routes apps/api/src/routes/assembly.ts and apps/api/src/routes/tags.ts already
-- use the service-role client (apps/api/src/lib/supabase.ts), so no API changes are needed.
-- After this migration, anon/authenticated direct RPC calls will receive permission denied.

-- update_clip_tags_with_history(uuid, uuid, jsonb, jsonb)
REVOKE EXECUTE ON FUNCTION update_clip_tags_with_history(uuid, uuid, jsonb, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION update_clip_tags_with_history(uuid, uuid, jsonb, jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION update_clip_tags_with_history(uuid, uuid, jsonb, jsonb) FROM authenticated;
GRANT EXECUTE ON FUNCTION update_clip_tags_with_history(uuid, uuid, jsonb, jsonb) TO service_role;

-- replace_section_clips(uuid, uuid, jsonb)
REVOKE EXECUTE ON FUNCTION replace_section_clips(uuid, uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION replace_section_clips(uuid, uuid, jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION replace_section_clips(uuid, uuid, jsonb) FROM authenticated;
GRANT EXECUTE ON FUNCTION replace_section_clips(uuid, uuid, jsonb) TO service_role;

-- ========== 20240020000000_audio_storage_bucket.sql ==========
-- Create the audio storage bucket for music file uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'audio',
  'audio',
  true,
  52428800, -- 50 MB
  ARRAY['audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav', 'audio/ogg', 'audio/aac', 'audio/mp4', 'audio/x-m4a']
)
ON CONFLICT (id) DO NOTHING;

-- Authenticated users can upload to their own folder
CREATE POLICY "Authenticated users can upload audio"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'audio');

-- Authenticated users can update their own uploads
CREATE POLICY "Authenticated users can update own audio"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'audio' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Public read access (bucket is public, but policy is needed for RLS)
CREATE POLICY "Public read access for audio"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'audio');

-- Authenticated users can delete their own uploads
CREATE POLICY "Authenticated users can delete own audio"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'audio' AND (storage.foldername(name))[1] = auth.uid()::text);

-- ========== 20260312000000_enforce_one_music_track_per_session.sql ==========
-- Enforce V1 contract: one active music track per session
-- If duplicates exist, keep the most recently created row per session_id.

with ranked as (
  select
    id,
    session_id,
    row_number() over (partition by session_id order by created_at desc) as rn
  from music_tracks
)
delete from music_tracks
where id in (select id from ranked where rn > 1);

-- Enforce at DB level
alter table music_tracks
  add constraint music_tracks_session_id_unique unique (session_id);

-- ========== 20260319000000_nullable_session_id_for_inbox.sql ==========
-- Migration 20260319000000: Support Inbox clips (session_id nullable) + direct clip ownership

-- 1) Add user_id to clips so inbox clips (no session) remain owned.
ALTER TABLE clips
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES users(id) ON DELETE CASCADE;

-- 2) Backfill user_id for existing clips via their session.
UPDATE clips c
SET user_id = s.user_id
FROM sessions s
WHERE c.session_id = s.id
  AND c.user_id IS NULL;

-- 3) Make session_id nullable to allow inbox items.
ALTER TABLE clips
  ALTER COLUMN session_id DROP NOT NULL;

-- 4) Enforce that every clip has an owner (directly), even if session_id is null.
ALTER TABLE clips
  ALTER COLUMN user_id SET NOT NULL;

-- 5) Helpful index for inbox queries
CREATE INDEX IF NOT EXISTS clips_user_id_session_id_idx ON clips (user_id, session_id);

-- 6) Update clips RLS to allow access by direct ownership OR via session ownership.
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clips_all_own_session ON clips;

CREATE POLICY clips_all_own ON clips FOR ALL
  USING (
    user_id = auth.uid()
    OR (
      session_id IS NOT NULL
      AND session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid())
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR (
      session_id IS NOT NULL
      AND session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid())
    )
  );

-- ========== 20260319000001_note_pins.sql ==========
-- Migration 20260319000001: Session-level timestamped note pins

CREATE TABLE IF NOT EXISTS note_pins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  timecode_ms integer NOT NULL,
  text text,
  audio_storage_path text,
  color text DEFAULT '#4ECDC4',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE note_pins ENABLE ROW LEVEL SECURITY;

-- Owner is derived from the parent session.
CREATE POLICY note_pins_all_own_session ON note_pins FOR ALL
  USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()))
  WITH CHECK (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

CREATE INDEX IF NOT EXISTS note_pins_session_id_timecode_idx ON note_pins (session_id, timecode_ms);

-- ========== 20260319000002_clip_share_tokens.sql ==========
-- Migration 20260319000002: Clip-level share tokens (keeps session-level tokens working)

ALTER TABLE share_tokens
  ADD COLUMN IF NOT EXISTS clip_id uuid REFERENCES clips(id) ON DELETE CASCADE;

-- One active (non-revoked) token per clip.
CREATE UNIQUE INDEX IF NOT EXISTS share_tokens_active_clip_unique
  ON share_tokens (clip_id)
  WHERE clip_id IS NOT NULL AND revoked_at IS NULL;

-- ========== 20260319000003_get_shared_clip_rpc.sql ==========
-- Migration 20260319000003: get_shared_clip RPC (anon-accessible clip share page)

CREATE OR REPLACE FUNCTION get_shared_clip(p_token uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
  v_clip_id uuid;
  v_session sessions%ROWTYPE;
  v_clip clips%ROWTYPE;
BEGIN
  -- Look up valid clip-level share token (clip_id must be present)
  SELECT st.session_id, st.clip_id INTO v_session_id, v_clip_id
  FROM share_tokens st
  WHERE st.token = p_token AND st.revoked_at IS NULL AND st.clip_id IS NOT NULL;

  IF v_session_id IS NULL OR v_clip_id IS NULL THEN
    RETURN NULL;
  END IF;

  -- Fetch session (for display context)
  SELECT * INTO v_session FROM sessions WHERE id = v_session_id;

  -- Fetch the bound clip (scoped to session as defense-in-depth)
  SELECT * INTO v_clip FROM clips WHERE id = v_clip_id AND session_id = v_session_id;

  IF v_clip.id IS NULL THEN
    RETURN NULL;
  END IF;

  RETURN json_build_object(
    'session', to_jsonb(v_session),
    'clip', to_jsonb(v_clip)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION get_shared_clip(uuid) TO anon;

-- ========== 20260319000004_get_shared_session_rpc_session_scope.sql ==========
-- Migration 20260319000004: tighten get_shared_session token scope (session-only tokens)

CREATE OR REPLACE FUNCTION get_shared_session(p_token uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id uuid;
  v_session sessions%ROWTYPE;
  v_music_track music_tracks%ROWTYPE;
  v_clips jsonb;
BEGIN
  -- Look up valid *session-level* share token (clip_id must be NULL)
  SELECT st.session_id INTO v_session_id
  FROM share_tokens st
  WHERE st.token = p_token AND st.revoked_at IS NULL AND st.clip_id IS NULL;

  IF v_session_id IS NULL THEN
    RETURN NULL;
  END IF;

  -- Fetch session
  SELECT * INTO v_session FROM sessions WHERE id = v_session_id;

  -- Fetch single music_track (V1: one track per session)
  SELECT * INTO v_music_track
  FROM music_tracks
  WHERE session_id = v_session_id
  LIMIT 1;

  -- Fetch clips with upload_status IN ('ready', 'processing'), ordered by recorded_at ASC
  SELECT COALESCE(
    (SELECT jsonb_agg(to_jsonb(cl) ORDER BY cl.recorded_at ASC)
     FROM clips cl
     WHERE cl.session_id = v_session_id AND cl.upload_status IN ('ready', 'processing')),
    '[]'::jsonb
  ) INTO v_clips;

  RETURN json_build_object(
    'session', to_jsonb(v_session),
    'music_track', CASE WHEN v_music_track.id IS NULL THEN NULL ELSE to_jsonb(v_music_track) END,
    'clips', COALESCE(v_clips, '[]'::jsonb)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION get_shared_session(uuid) TO anon;

-- ========== 20260320000000_phase2_clip_tags.sql ==========
-- Add Phase 2 clip tagging columns
-- First add section_id column (nullable for existing records)
ALTER TABLE clips ADD COLUMN IF NOT EXISTS section_id TEXT;
-- Then add tagging columns
ALTER TABLE clips ADD COLUMN IF NOT EXISTS type_tag TEXT;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS feel_tags TEXT[] DEFAULT '{}';

-- Create composite index for efficient filtering
CREATE INDEX IF NOT EXISTS idx_clips_session_section_type ON clips (session_id, section_id, type_tag);

-- ========== 20260320000001_phase2_share_mode.sql ==========
-- Add Phase 2 share mode column
ALTER TABLE share_tokens ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'lightweight' CHECK (mode IN ('lightweight', 'structured'));

-- ========== 20260320000002_clip_responses.sql ==========
-- Viewer responses to shared clips (edge function uses service role; RLS for direct API access)

CREATE TABLE clip_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clip_id uuid NOT NULL REFERENCES clips(id) ON DELETE CASCADE,
  token_id uuid REFERENCES share_tokens(id) ON DELETE SET NULL,
  text text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE clip_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY clip_responses_anon_insert ON clip_responses
  FOR INSERT TO anon
  WITH CHECK (true);

CREATE POLICY clip_responses_owner_select ON clip_responses
  FOR SELECT TO authenticated
  USING (
    clip_id IN (SELECT id FROM clips WHERE user_id = auth.uid())
  );

-- ========== 20260401000000_group_participants.sql ==========
-- Migration 20260401000000: Realtime group participants

CREATE TABLE group_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  display_name text NOT NULL,
  color text NOT NULL,
  role text NOT NULL DEFAULT 'dancer' CHECK (role IN ('choreographer', 'dancer')),
  position_x float,
  position_y float,
  position_note text,
  last_seen_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE (session_id, user_id)
);

ALTER TABLE group_participants ENABLE ROW LEVEL SECURITY;

-- SECURITY DEFINER helper to evaluate membership without recursive RLS policy evaluation.
CREATE OR REPLACE FUNCTION public.is_session_member(target_session_id uuid)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requester_id uuid := auth.uid();
BEGIN
  IF requester_id IS NULL THEN
    RETURN false;
  END IF;

  RETURN EXISTS (
    SELECT 1
    FROM sessions s
    WHERE s.id = target_session_id
      AND s.user_id = requester_id
  )
  OR EXISTS (
    SELECT 1
    FROM group_participants gp
    WHERE gp.session_id = target_session_id
      AND gp.user_id = requester_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.is_session_member(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_session_member(uuid) TO authenticated;

-- Session owner or session participant can read participant rows.
CREATE POLICY group_participants_select_session_members ON group_participants FOR SELECT
  TO authenticated
  USING (public.is_session_member(session_id));

-- Only the row owner can update their participant row.
CREATE POLICY group_participants_update_own ON group_participants FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

ALTER TABLE group_participants REPLICA IDENTITY FULL;

-- ========== 20260401000001_broadcasts.sql ==========
-- Migration 20260401000001: Realtime session broadcasts

CREATE TABLE broadcasts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message text NOT NULL CHECK (char_length(message) <= 60),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE broadcasts ENABLE ROW LEVEL SECURITY;

-- Session owner or participant can read broadcasts.
CREATE POLICY broadcasts_select_session_members ON broadcasts FOR SELECT
  TO authenticated
  USING (public.is_session_member(session_id));

-- Authenticated users can insert their own broadcast rows.
CREATE POLICY broadcasts_insert_own_sender ON broadcasts FOR INSERT
  TO authenticated
  WITH CHECK (sender_id = auth.uid());

ALTER TABLE broadcasts REPLICA IDENTITY FULL;

-- ========== 20260401000002_moments.sql ==========
-- Migration 20260401000002: Moments table with formation + quality JSONB columns

CREATE TABLE moments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  name text NOT NULL,
  beat_position_ms integer NOT NULL DEFAULT 0,
  formation jsonb,
  quality jsonb,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE moments ENABLE ROW LEVEL SECURITY;

CREATE POLICY moments_select_session_members
ON moments
FOR SELECT
TO authenticated
USING (public.is_session_member(session_id));

CREATE POLICY moments_insert_session_members
ON moments
FOR INSERT
TO authenticated
WITH CHECK (public.is_session_member(session_id));

CREATE POLICY moments_update_session_members
ON moments
FOR UPDATE
TO authenticated
USING (public.is_session_member(session_id))
WITH CHECK (public.is_session_member(session_id));

CREATE POLICY moments_delete_session_owner
ON moments
FOR DELETE
TO authenticated
USING (session_id IN (SELECT id FROM sessions WHERE user_id = auth.uid()));

ALTER TABLE moments REPLICA IDENTITY FULL;

CREATE INDEX idx_moments_session_position ON moments (session_id, position);

-- ========== 20260402000000_moments_unique_session_position.sql ==========
-- Migration 20260402000000: Enforce unique ordering for session moments

ALTER TABLE moments
ADD CONSTRAINT moments_session_id_position_unique
UNIQUE (session_id, position);

-- ========== 20260402000001_moments_position_ordering_helpers.sql ==========
-- Moments position ordering helpers:
-- - moments_session_id_position_unique_constraint_exists(): verify unique constraint presence
-- - create_moment_atomic_with_position(): atomic insert using per-session advisory lock

CREATE OR REPLACE FUNCTION moments_session_id_position_unique_constraint_exists()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE c.conname = 'moments_session_id_position_unique'
      AND t.relname = 'moments'
      AND t.relnamespace = 'public'::regnamespace
  );
END;
$$;

CREATE OR REPLACE FUNCTION create_moment_atomic_with_position(
  p_session_id uuid,
  p_name text,
  p_beat_position_ms integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_position integer;
  v_m moments%ROWTYPE;
BEGIN
  -- Serialize position allocation per session so duplicate positions cannot be created,
  -- even if the unique constraint migration isn't applied yet.
  PERFORM pg_advisory_xact_lock(hashtext(p_session_id::text));

  SELECT COALESCE(MAX(m.position), -1) + 1
  INTO v_position
  FROM moments m
  WHERE m.session_id = p_session_id;

  INSERT INTO moments (session_id, name, beat_position_ms, position, formation, quality)
  VALUES (p_session_id, p_name, p_beat_position_ms, v_position, NULL, NULL)
  RETURNING * INTO v_m;

  RETURN to_jsonb(v_m);
END;
$$;

-- Lock down RPCs to service_role only (API uses service-role Supabase client).
REVOKE EXECUTE ON FUNCTION moments_session_id_position_unique_constraint_exists() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION moments_session_id_position_unique_constraint_exists() FROM anon;
REVOKE EXECUTE ON FUNCTION moments_session_id_position_unique_constraint_exists() FROM authenticated;
GRANT EXECUTE ON FUNCTION moments_session_id_position_unique_constraint_exists() TO service_role;

REVOKE EXECUTE ON FUNCTION create_moment_atomic_with_position(uuid, text, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_moment_atomic_with_position(uuid, text, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION create_moment_atomic_with_position(uuid, text, integer) FROM authenticated;
GRANT EXECUTE ON FUNCTION create_moment_atomic_with_position(uuid, text, integer) TO service_role;

-- ========== 20260403000000_session_share_token_atomic.sql ==========
-- Session share token atomic creation helper:
-- - create_or_get_session_share_token(): atomic create-or-get for session share tokens

CREATE OR REPLACE FUNCTION create_or_get_session_share_token(p_session_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  existing_token uuid;
  new_token uuid;
BEGIN
  -- Lock on session row to serialize owners
  PERFORM pg_advisory_xact_lock(hashtext(p_session_id::text));

  -- Check for existing active session token
  SELECT token INTO existing_token
  FROM share_tokens
  WHERE session_id = p_session_id AND clip_id IS NULL AND revoked_at IS NULL
  LIMIT 1 FOR UPDATE SKIP LOCKED;

  IF existing_token IS NOT NULL THEN
    RETURN existing_token;
  END IF;

  -- Create new token
  new_token := gen_random_uuid();
  
  INSERT INTO share_tokens (session_id, token, clip_id)
  VALUES (p_session_id, new_token, NULL);
  
  RETURN new_token;
END;
$$;

-- Lock down RPC to service_role only (API uses service-role Supabase client).
REVOKE EXECUTE ON FUNCTION create_or_get_session_share_token(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_or_get_session_share_token(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION create_or_get_session_share_token(uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION create_or_get_session_share_token(uuid) TO service_role;

-- ========== 20260403000001_session_share_tokens_unique.sql ==========
-- Migration: Add unique constraint for active session-level share tokens
-- Ensures only one non-revoked token can exist per session (clip_id IS NULL)

CREATE UNIQUE INDEX IF NOT EXISTS share_tokens_active_session_unique
  ON share_tokens (session_id)
  WHERE clip_id IS NULL AND revoked_at IS NULL;

-- ========== 20260403000002_session_phrase.sql ==========
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS phrase TEXT;

-- ========== 20260404000000_loops.sql ==========
-- Create loops table
CREATE TABLE IF NOT EXISTS loops (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  source_url text NOT NULL,
  start_ms integer NOT NULL,
  end_ms integer NOT NULL,
  color text NOT NULL,
  name text NOT NULL,
  created_by uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE loops ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- SELECT - session members
CREATE POLICY loops_select_session_members ON loops
  FOR SELECT USING (public.is_session_member(session_id));

-- INSERT - session members
CREATE POLICY loops_insert_session_members ON loops
  FOR INSERT WITH CHECK (public.is_session_member(session_id));

-- UPDATE - session members
CREATE POLICY loops_update_session_members ON loops
  FOR UPDATE USING (public.is_session_member(session_id));

-- DELETE - session owner only
CREATE POLICY loops_delete_session_owner ON loops
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM sessions
      WHERE sessions.id = loops.session_id
      AND sessions.user_id = auth.uid()
    )
  );

-- Index for performance
CREATE INDEX idx_loops_session_source ON loops (session_id, source_url);

-- Set REPLICA IDENTITY FULL for replication
ALTER TABLE loops REPLICA IDENTITY FULL;

-- ========== 20260405000000_clip_trim_lineage.sql ==========
-- Add clip_type column with MINE/REF distinction
ALTER TABLE clips ADD COLUMN IF NOT EXISTS clip_type TEXT CHECK (clip_type IN ('MINE', 'REF'));

-- Add trimmed_from_clip_id foreign key for lineage tracking
ALTER TABLE clips ADD COLUMN IF NOT EXISTS trimmed_from_clip_id uuid REFERENCES clips(id) ON DELETE SET NULL;

-- Add index for efficient queries of trimmed clips
CREATE INDEX IF NOT EXISTS idx_clips_trimmed_from ON clips (trimmed_from_clip_id) WHERE trimmed_from_clip_id IS NOT NULL;

-- ========== 20260406000000_session_quality_target.sql ==========
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS quality_target JSONB;

-- ========== 20260407000000_ref_clip_fields.sql ==========
-- Add REF clip fields to clips table (excluding clip_type which is added in 20260405000000_clip_trim_lineage.sql)
ALTER TABLE clips 
ADD COLUMN IF NOT EXISTS url text,
ADD COLUMN IF NOT EXISTS thumbnail_url text,
ADD COLUMN IF NOT EXISTS start_ms integer DEFAULT 0;

-- ========== 20260408000000_clip_genealogy.sql ==========
-- Creative genealogy — PRD §1
-- Adds bidirectional lineage pointers for clips, including note-trigger origins.

ALTER TABLE clips ADD COLUMN IF NOT EXISTS parent_clip_id UUID REFERENCES clips(id) ON DELETE SET NULL;
ALTER TABLE clips ADD COLUMN IF NOT EXISTS triggered_by_note_id UUID REFERENCES note_pins(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_clips_parent_clip_id ON clips(parent_clip_id) WHERE parent_clip_id IS NOT NULL;

-- ========== 20260409000000_audio_bucket.sql ==========
-- Audio bucket idempotent guard (bucket created in 20240020000000_audio_storage_bucket.sql)
-- This migration ensures the audio bucket exists for environments that skipped the earlier migration.
INSERT INTO storage.buckets (id, name, public)
  VALUES ('audio', 'audio', true)
  ON CONFLICT (id) DO NOTHING;

-- RLS policies (idempotent — skip if already exist)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Authenticated users can upload audio'
  ) THEN
    EXECUTE 'CREATE POLICY "Authenticated users can upload audio"
      ON storage.objects FOR INSERT
      TO authenticated
      WITH CHECK (bucket_id = ''audio'')';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Public read access for audio'
  ) THEN
    EXECUTE 'CREATE POLICY "Public read access for audio"
      ON storage.objects FOR SELECT
      TO public
      USING (bucket_id = ''audio'')';
  END IF;
END $$;

-- ========== 20260410000000_structured_feedback.sql ==========
create table if not exists public.structured_feedback (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  statement text,
  questions text,
  observations text,
  opinions text,
  created_at timestamptz not null default now()
);

alter table public.structured_feedback enable row level security;

create policy structured_feedback_insert_participants
  on public.structured_feedback
  for insert
  to authenticated
  with check (public.is_session_member(session_id));

create policy structured_feedback_select_owner
  on public.structured_feedback
  for select
  to authenticated
  using (
    session_id in (
      select id
      from public.sessions
      where user_id = auth.uid()
    )
  );

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clips_id_session_id_key'
      and conrelid = 'public.clips'::regclass
  ) then
    alter table public.clips
      add constraint clips_id_session_id_key unique (id, session_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'structured_feedback_clip_session_fk'
      and conrelid = 'public.structured_feedback'::regclass
  ) then
    alter table public.structured_feedback
      add constraint structured_feedback_clip_session_fk
      foreign key (clip_id, session_id)
      references public.clips(id, session_id)
      on delete cascade;
  end if;
end $$;

-- ========== 20260418000000_drill_sequences.sql ==========
create table if not exists public.drill_sequences (
  session_id uuid primary key references public.sessions(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.drill_sequences enable row level security;

drop policy if exists "drill_sequences_select_owner_or_participant" on public.drill_sequences;
create policy "drill_sequences_select_owner_or_participant"
on public.drill_sequences
for select
using (
  exists (
    select 1
    from public.sessions s
    where s.id = drill_sequences.session_id
      and s.user_id = auth.uid()
  )
  or exists (
    select 1
    from public.group_participants gp
    where gp.session_id = drill_sequences.session_id
      and gp.user_id = auth.uid()
  )
);

drop policy if exists "drill_sequences_modify_owner_only" on public.drill_sequences;
create policy "drill_sequences_modify_owner_only"
on public.drill_sequences
for all
using (
  exists (
    select 1
    from public.sessions s
    where s.id = drill_sequences.session_id
      and s.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.sessions s
    where s.id = drill_sequences.session_id
      and s.user_id = auth.uid()
  )
);

-- ========== 20260419000000_moments_last_modified_at.sql ==========
ALTER TABLE moments
ADD COLUMN IF NOT EXISTS last_modified_at timestamptz DEFAULT now();

CREATE OR REPLACE FUNCTION set_moments_last_modified_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.last_modified_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS moments_set_last_modified_at ON moments;

CREATE TRIGGER moments_set_last_modified_at
BEFORE UPDATE ON moments
FOR EACH ROW
EXECUTE FUNCTION set_moments_last_modified_at();

-- ========== 20260519000000_clip_marking_fingerprints.sql ==========
-- Marking search: compact motion fingerprints per clip (choreography similarity).

CREATE TABLE IF NOT EXISTS clip_marking_fingerprints (
  clip_id uuid PRIMARY KEY REFERENCES clips(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fingerprint jsonb NOT NULL,
  dims integer NOT NULL,
  source text NOT NULL DEFAULT 'mux_thumbnails',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clip_marking_fingerprints_user_id_idx
  ON clip_marking_fingerprints (user_id);

ALTER TABLE clip_marking_fingerprints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clip_marking_fingerprints_own ON clip_marking_fingerprints;

CREATE POLICY clip_marking_fingerprints_own ON clip_marking_fingerprints
  FOR ALL
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
